---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Рок-гурт
description: Навчися програмувати власні музичні інструменти
version: 4
last_tested: 2018-10-12
steps:
- title: Вступ
  completion: engaged
- title: Спрайти
- title: Сцена
- title: Створення барабана
- title: 'Завдання: вдоскональ свій барабан'
  challenge: true
- title: Створення співачки
  completion: internal
- title: Образи
- title: 'Завдання: покращи свій гурт'
  challenge: true
- title: Що далі?
