---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: Learn how to code your own musical instruments
version: 4.1.1
last_tested: 2018-10-12
steps:
- title: Introduction
  completion: engaged
- title: Sprites
- title: The Stage
- title: Making a drum
- title: 'Challenge: improve your drum'
  challenge: true
- title: Making a singer
  completion: internal
- title: Costumes
- title: 'Challenge: improve your band'
  challenge: true
- title: What next?
