hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: Learn how to code your own musical instruments
version: 4.1.0
last_tested: 2019-10-12
steps: 
- title: Introduction
- title: Sprites
- title: The Stage
- title: Making a drum
- title: "Challenge: improve your drum"
- title: Making a singer
- title: Costumes
- title: "Challenge: improve your band"
