---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: Learn how to code your own musical instruments
version: 4.1.1
last_tested: 2018-10-12
steps:
- title: Introduction
- title: Sprites
  completion:
  - engaged
- title: The Stage
- title: Make a drum
- title: Make a singer
- title: Costumes
  completion:
  - internal
- title: Challenge
  completion:
  - external
- title: What next?
