---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: रॉक बैंड
description: अपने स्वयं के संगीत वाद्ययंत्र को कोड करना सीखें
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: भूमिका
  - 
    title: स्प्राइट्स
  - 
    title: स्टेज
  - 
    title: ड्रम बनाना
  - 
    title: "चुनौती: अपने ड्रम में सुधार करें"
    challenge: true
  - 
    title: गायक बनाना
  - 
    title: पोशाकें
  - 
    title: "चुनौती: अपने बैंड में सुधार करें"
    challenge: true
  - 
    title: "आगे क्या?"


