---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Рок група
description: Научи како да програмираш сопствене музичке уређаје
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Увод
  - 
    title: Sprites
  - 
    title: The Stage
    completion:
      - engaged
  - 
    title: Making a drum
  - 
    title: 'Challenge: improve your drum'
    challenge: true
  - 
    title: Making a singer
  - 
    title: Costumes
    completion:
      - internal
  - 
    title: 'Challenge: improve your band'
    challenge: true
  - 
    title: What next?
