---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: 摇滚乐队
description: 学习如何编自己的乐器
version: 4.1.1
last_tested: 2018-10-12
steps:
- title: 简介
  completion: engaged
- title: 角色
- title: 舞台
- title: 制作一面鼓
- title: 挑战：改进你的鼓
  challenge: true
- title: 创建一个歌手
  completion: internal
- title: 造型
- title: 挑战：改进你的乐队
  challenge: true
- title: 接下来还有什么？
