---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock bend
description: U ovom projektu naučit ćeš kako programirati vlastite glazbene instrumente!
version: 4.1.1
last_tested: 2018-10-12
steps:
- title: Uvod
- title: Likovi
- title: Pozornica
  completion:
  - engaged
- title: Napravi bubanj
- title: 'Izazov: poboljšaj svoj bubanj'
  challenge: true
- title: Dodaj pjevačicu
- title: Kostimi
  completion:
  - internal
- title: 'Izazov: poboljšaj svoj bend'
  challenge: true
- title: Što dalje?
