---
hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Banda de Rock
description: Aprende cómo codificar tus propios instrumentos musicales
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
  - title: Introducción
  - title: Lo que necesitarás
  - title: Objetos
  - title: El Escenario
  - title: Crear un tambor
  - title: "Desafío: mejora tu tambor"
  - title: Crear un cantante
  - title: Disfraces
  - title: "Desafío: cambia el disfraz de tu tambor"
  - title: "Desafío: crea tu propia banda"
