---
hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rock-Band
description: Lerne deine eigenen Musikinstrumente zu programmieren
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
  - title: Einleitung
  - title: Was du brauchen wirst
  - title: Figuren
  - title: Die Bühne
  - title: Eine Trommel machen
  - title: "Herausforderung: Verbessere deine Trommel"
  - title: Einen Sänger machen
  - title: Kostüme
  - title: "Herausforderung: Ändere das Kostüm deiner Trommel"
  - title: "Herausforderung: Mache deine eigene Band"
