---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Formație rock
description: Învață cum să programezi propriile tale instrumente muzicale
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Introducere
  - 
    title: Personaje
  - 
    title: Scena
  - 
    title: Creează o toba
  - 
    title: "Provocare: îmbunătățește-ți toba"
    challenge: true
  - 
    title: Creează o cântăreață
  - 
    title: Costume
  - 
    title: "Provocare: îmbunătățește-ți formația"
    challenge: true
  - 
    title: "What next?"


