---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Band rock
description: Pelajari cara membuat kode alat musik Kamu sendiri
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Pengantar
  - 
    title: Sprite
  - 
    title: Panggung
    completion:
      - engaged
  - 
    title: Membuat drum
  - 
    title: 'Tantangan: tingkatkan drum kamu'
    challenge: true
  - 
    title: Membuat penyanyi
  - 
    title: Kostum
    completion:
      - internal
  - 
    title: 'Tantangan: tingkatkan band kamu'
    challenge: true
  - 
    title: What next?
