---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rockegyüttes
description: Ismerd meg, hogyan programozhatsz saját hangszereket
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Bevezetés
  - 
    title: Szereplők
  - 
    title: A színpad
    completion:
      - engaged
  - 
    title: Készíts egy dobot
  - 
    title: 'Kihívás: fejleszd a dobot'
    challenge: true
  - 
    title: Készíts egy énekest
  - 
    title: Jelmezek
    completion:
      - internal
  - 
    title: 'Kihívás: fejleszd a zenekart'
    challenge: true
  - 
    title: What next?
