---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Banda de Rock
description: Aprende cómo codificar tus propios instrumentos musicales
version: 4.1.1
last_tested: 2018-10-12
steps:
- title: Introducción
  completion: engaged
- title: Objetos
- title: El Escenario
- title: Haciendo un tambor
- title: 'Desafío: mejora tu tambor'
  challenge: true
- title: Haciendo un cantante
  completion: internal
- title: Disfraces
- title: 'Desafío: mejora tu banda'
  challenge: true
- title: "¿Qué sigue?"
