---
hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rocková skupina
description: V tomto projekte sa naučíš ako naprogramovať hudobné nástroje!
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
- title: Rocková skupina
  completion: engaged
