---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Ροκ μπάντα
description: Μάθε πώς να προγραμματίζεις τα δικά σου μουσικά όργανα
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Εισαγωγή
  - 
    title: Αντικείμενα
  - 
    title: Το σκηνικό
    completion:
      - engaged
  - 
    title: Κάνοντας ένα τύμπανο
  - 
    title: 'Πρόκληση: βελτίωσε το τύμπανό σου'
    challenge: true
  - 
    title: Κάνοντας μία τραγουδίστρια
  - 
    title: Ενδυμασίες
    completion:
      - internal
  - 
    title: 'Πρόκληση: βελτίωσε τη μπάντα σου'
    challenge: true
  - 
    title: What next?
