---
hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rok grupa
description: Nauči kako da programiraš sopstvene muzičke instrumente
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
- title: Uvod
- title: Šta će ti biti potrebno
- title: Likovi (sprites)
  completion:
  - engaged
- title: Pozornica (stage)
- title: Pravljenje bubnja
- title: 'Izazov: poboljšaj svoj bubanj'
- title: Stvaranje pjevačice
  completion:
  - internal
- title: Kostimi (costumes)
- title: 'Izazov: promijeni kostim bubnja'
- title: 'Izazov: napravi svoju grupu'
