---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Groupe de rock
description: Apprends à programmer tes propres instruments de musique
version: 4.1.1
last_tested: 2018-10-12
steps:
- title: Introduction
- title: Sprites
- title: La scène
  completion:
  - engaged
- title: Créer un tambour
- title: 'Défi: Améliore ton tambour'
  challenge: true
- title: Créer un chanteur
- title: Costumes
  completion:
  - internal
- title: 'Défi: Améliore ton groupe'
  challenge: true