---
hero_image: images/hero-rock-band-large.png
listed: true
copyedit: false
title: Rock band
description: In questo progetto imparerai come programmare il tuo strumento musicale!
version: 4.1.1
last_tested: 2018-10-12
steps:
  - 
    title: Introduzione
  - 
    title: Sprite
  - 
    title: Lo Stage (palco)
    completion:
      - engaged
  - 
    title: Creare un tamburo
  - 
    title: 'Sfida: migliora il tuo tamburo'
    challenge: true
  - 
    title: Creare un cantante
  - 
    title: I Costumi
    completion:
      - internal
  - 
    title: 'Sfida: migliora la tua banda'
    challenge: true
  - 
    title: What next?
